polars.exceptions.OutOfBoundsError
==================================

.. currentmodule:: polars.exceptions

.. autoexception:: OutOfBoundsError